spring:
#  datasource:
#    url: jdbc:mysql://avnadmin:AVNS_1AXxTPaaCHAVyiowL-p@read-corner-db-cloud1-read-corner-db-cloud.d.aivencloud.com:16394/read-corner-db?createDatabaseIfNotExist=true&ssl-mode=REQUIRED
#    username: avnadmin
#    password: AVNS_1AXxTPaaCHAVyiowL-p
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    hikari:
#      maximum-pool-size: 10
  datasource:
    url: jdbc:mysql://localhost:3306/read-corner-library1-db?createDatabaseIfNotExist=true
    username: root
    password: m.A0121433211
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    defer-datasource-initialization: true
    sql:
      init:
        mode: never
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
  security:
    user.name: mgaber
    user.password: m123456
  main:
    banner-mode: off
  logging:
    level:
      root: warn
      org:
        hibernate:
          sql: debug
          orm.jdbc.bind: trace
        springframework: DEBUG
  mail:
    host: smtp.gmail.com
    port: 587
    username: eng.m.gaber3@gmail.com
    password: hodaiiakhahuzxvz
    properties:
      mail:
        smtp:
          ssl.trust: "*"
          auth: true
          starttls:
            enable: true
application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000 # 1 day
      refresh-token:
        expiration: 604800000 # 7 days
  mailing:
    frontend:
      activation-url: http://localhost:5173/verifyEmail
      reset-pass-url: http://localhost:5173/resetPassword
  file:
    uploads:
      photos-output-path: ./uploads
springdoc:
  default-produces-media-type: application/json
server:
  port: 8080

stripe:
  api.key: sk_test_51PwviPKa4rteRNqOAvjBAjaGPoBapWI68t3mq5y4GjQPy0OvuAkWLpe07KU0o4Aj32WiE3uAF7cbiIq279IdenuO00NaQI6wNP

cloudinary:
  cloud-name: dng1pgyfx
  api-key : 574771754334586
  api-secret : tgCQFkaJfjusKoQlXJmFJu8gFv4
  folder: Books

front-base-url: http://localhost:5173

